### ISSUE TITLE
Failed to merge: The operation couldn’t be completed. (CDEErrorDomain error 204.)

### ISSUE THREAD

**Issue by tuckerwales** [drewmccormack/ensembles#176]
I was using Ensembles in my app (with Core Data), then I ripped Core Data out to play around with Parse.

However, now I've decided to go with Core Data again (:/) - I added a new model and am now getting this new error.

I know it's because my new model is a newer version that the one in the cloud, but how do I resolve this?

Thanks.

**Comment by pventura1976** [comment]
I'm having the same issue but I think it could be in a different context:

2015-02-13 09:45:39.121 kPlant[1642:167378] Sync failed: Error Domain=CDEErrorDomain Code=204 "The operation couldn’t be completed. (CDEErrorDomain error 204.)"
2015-02-13 09:46:09.416 kPlant[1642:167378] Sync failed: Error Domain=CDEErrorDomain Code=204 "The operation couldn’t be completed. (CDEErrorDomain error 204.)"
2015-02-13 09:46:39.702 kPlant[1642:167378] Sync failed: Error Domain=CDEErrorDomain Code=204 "The operation couldn’t be completed. (CDEErrorDomain error 204.)"

The version of the app available on AppStore works fine, but not the new version that has model changes (nothing that a lightweight migration can't handle). I've tried to delete iCloud existing data but the error is still the same. There is no files at ~/Library/Mobile Documents

Any clue?

**Comment by drewmccormack** [comment]
That is caused by not having all the different model versions in your momd. 

Is it possible you did a sync with an intermediate version of your model, that is no longer one of the versions? 

To clear the data and start again:

1. Deleech your ensemble
2. Remove any files in Mobile Documents on all devices
3. Leech your ensemble again.

The problems are probably because you are not deleeching, and the old sync data is cached locally on the device.

If you don’t want to explicitly deleech, you can also just remove the cached data. It is stored in Application Support.

Drew

**Comment by pventura1976** [comment]
May be this has happened during the development of the new version. But my real concern now is how this will affect users when I upload this new version. They will loose all data?

**Comment by drewmccormack** [comment]
The problem should not happen to your customers. I think it only arose because you probably made changed your most recent model a few times without creating a revision. In you end users case, they will jump from the old model version to the new, and all the versions will be present.

But you should definitely test. Install the App Store app, sync a bit, then install the new version and see if that works.

Kind regards,
Drew

**Comment by pventura1976** [comment]
Thank you very much, I'm on it :-)
