### ISSUE TITLE
CoreData: Failed to load optimized model at path

### ISSUE THREAD

**Issue by asciiz** [drewmccormack/ensembles#205]
OS X 10.11, Xcode 7, Ensembles 2.2.3

If "initWithEnsembleIdentifier:" is called, the following message is logged:

CoreData: Failed to load optimized model at path:
...Ensembles.framework/Versions/A/Resources/CDEEventStoreModel.momd/CDEEventStoreModel_2.omo

**Comment by drewmccormack** [comment]
Please try the more recent releases (eg 2.3.2)

**Comment by jefarmstrong** [comment]
I just downloaded the latest version 2 and I'm getting the same error. It's while running on ios simulator.

**Comment by drewmccormack** [comment]
So you have a Mac app, and you are using the binary Ensembles.framework?

**Comment by jefarmstrong** [comment]
no, it's an iOS app, and yes I added the Ensembles.framework and Ensembles.bundle to the project. I just tried connecting to iCloud using the CDECloudKitFileSystem and it seemed to work.

**Comment by drewmccormack** [comment]
What is really odd is that it seems to have found the model in the framework, and there shouldn't be one there. Maybe something went wrong with the build:
...Ensembles.framework/Versions/A/Resources/CDEEventStoreModel.momd/CDEEventStoreModel_2.omo

Drew

**Comment by jefarmstrong** [comment]
I believe that it's getting the momd from the Ensembles.bundle, not the framework.  
CoreData: Failed to load optimized model at path '/var/mobile/Containers/Bundle/Application/1390FEB6-94F0-479D-87C7-35C0EF3085EA/Fishie.app/CDEEventStoreModel.momd/CDEEventStoreModel_2.omo'

It's not really a problem, afaik, since it's just the optimized model and everything will work fine without it.
