### ISSUE TITLE
Dropbox v2 Integration - SwiftyDropbox SDK

### ISSUE THREAD

**Issue by LubosPlavucha** [drewmccormack/ensembles#232]
Currently, it is possible to use the Dropbox backend for synchronization, using Dropbox SDK.
Is the Ensemble also working with the new Dropbox API v2 (SwiftyDropbox SDK) ? If not, are you planning to work on this ?

**Comment by pronebird** [comment]
I am not able to compile Ensembles with Dropbox SDK. There are missing x86_64 symbols... old DB SDK does not show up in Pods at all...

**Comment by drewmccormack** [comment]
I am planning to integrate Dropbox API v2 quite soon, but will probably just use their REST API rather than Swift. (I have never been impressed by the quality of their native APIs, and it is one more link in the chain to break.)

Here is a fork of Dropbox SDK v1. You can use it with Pods or compile yourself.

https://github.com/drewmccormack/dropbox-sdk-ios
