### ISSUE TITLE
New dropbox Api v2

### ISSUE THREAD

**Issue by Simone67** [drewmccormack/ensembles#255]
Hello Drew,
thank you for your update to new dropbox api v2.
how can I update the new Api using Pod file?

```
pod "Ensembles"," ~> 1.0"
pod "Ensembles/Dropbox","~> 1.0"
```

Thank you

**Comment by drewmccormack** [comment]
We haven't made a release with this yet, but you can use it directly by getting Cocoapods to use the most recent master. If you look in the most recent master, you will see this:

```
  s.subspec 'DropboxV2' do |ss|
    # Bump deployment targets to match ObjectiveDropboxOfficial's
    ss.ios.deployment_target = '8.0'
    ss.osx.deployment_target = '10.10'
    ss.dependency 'Ensembles/Core'
    ss.dependency 'ObjectiveDropboxOfficial', '~> 3.0.18'
    ss.source_files = 'Framework/Extensions/CDEDropboxV2CloudFileSystem.{h,m}'
  end
```

Will probably make a new release next week.

Drew

**Comment by Simone67** [comment]
thank you Drew, I will wait nex week for the next release.
Greetings

**Comment by Simone67** [comment]
Hello Drew,
thanks to updated to 1.7 but I use Pod file to import Ensembles and it still 1.6.11 rev
        pod 'Ensembles','~> 1.0'
        pod 'Ensembles/Dropbox','~> 1.0'
There something wrong in my Podfile?
Thanks

**Comment by Simone67** [comment]
pod 'Ensembles','> 1.0'
pod 'Ensembles/Dropbox','> 1.0'

**Comment by drewmccormack** [comment]
Sorry. Looks like Dropbox bumped their deployment target. 

Have fixed it and pushed Cocoapods spec. Requires iOS 9.0 due to Dropbox restrictions.

**Comment by Simone67** [comment]
In your specs:

> Incorporating Ensembles in an iOS Project
> To add Ensembles to your App's Xcode Project with CocoaPods...
> Add the following to your Podfile
> platform :ios, '7.0'
> pod "Ensembles", "~> 1.0"

but when I do: -->  pod install
the release installed is 1.6.2 n ot 1.7(with dropboxv2)

I do not donwload the Ensembles framework but I use Podfile

I'm sorry to disturb you but can't solve the dropboxv2 problem becouse when I do pod install nothing change...

**Comment by drewmccormack** [comment]
Yesterday the latest version (1.7) was not on Cocoapods due to the problem I mentioned. But I pushed it this morning successfully, so it should be working.

I think you problem now is that in order to use DropboxV2, you need to target iOS 9.0. I guess that Cocoapods sees that 1.7 requires iOS 9.0, and you are deploying to 7.0, so it decides you can't upgrade. If you change your deployment target to 9.0 I think it will work.

(Note that this requirement has nothing to do with Ensembles, but is a requirement of Dropbox SDK v2)

**Comment by Simone67** [comment]
this is my Podfile:

> platform :ios, '9.0'
> 
> target 'ELDORADO' do
>         pod 'Ensembles','~> 1.0'
>         pod 'Ensembles/Dropbox','~> 1.0'
>         pod 'SSKeychain', '~> 1.2.2'
>         pod 'VENTouchLock', '~> 1.0'
>         pod 'Fabric'
>         pod 'Crashlytics', '~> 3.8'
>         pod 'SWTableViewCell', '~> 0.3.7'
> end

when I do 'pod install' it install:

> Analyzing dependencies
> Downloading dependencies
> Using Crashlytics (3.8.3)
> Installing Dropbox-iOS-SDK (1.3.13)
> Installing Ensembles (1.6.2)

so the 1.6.2 was installed and not 1.7 (platform is set to 9.0)

**Comment by drewmccormack** [comment]
The fact that you removed the dropbox dependency from the podfile, and Cocoapods is still installing Dropbox, tells me it is a caching problem with Cocoapods. For some reason it is not picking up the changes in your podfile.

You can see Ensembles 1.7 does exist here: https://cocoapods.org/?q=Ensembles <https://cocoapods.org/?q=Ensembles>

I am no expert on Cocoapods, because I never use it, but perhaps you need to use ‘pod update’ instead of ‘pod install’. Or perhaps you need to clear the cocoapods cache: https://gist.github.com/mbinna/4202236 <https://gist.github.com/mbinna/4202236>

Any Cocoapods experts want to chip in?

Drew

**Comment by Simone67** [comment]
well, it's works using "pod update".
Hope this info could be usefull for others user.
Thank you Drew you are really kind.
I appreciate.
Greetings
