### ISSUE TITLE
Allow custom migrators, so that structured store backends like parse can be used

### ISSUE THREAD

**Issue by drewmccormack** [drewmccormack/ensembles#75]
There are many BaaSes. They have basic entity models. They could be leveraged by mirroring the ensembles internal model. This could be done at the migrator level.

**Comment by erndev** [comment]
Hi @drewmccormack 

Revisiting this old thread, i had a question about. 
Recently, Ensembles has included CloudKit support, which works more or less like Parse (both being record-based instead of file based), 
Based on your experience implementing it, do you think now Parse could be an option as a store backend?  

it would be a great option for Mac apps that require syncing, but do not want to be in the Mac App Store.

cheers

**Comment by drewmccormack** [comment]
Yes, Parse could certainly be used. Note that Ensembles doesn't work directly with the CloudKit/Parse records. Instead it just uses the records to store blobs of data, i.e. files. So it uses it more like a file store than the way it was intended to be used.

But yes, you could quite easily take the CloudKit backend, and rewrite it to work with Parse calls instead. If you want to try it yourself, I am happy to offer guidance, but I don't really have time to do this at the moment. 

Dropbox Core API is not a bad option if iCloud is off limits.

**Comment by erndev** [comment]
great! i am working on a mac app, and will definitely use ensembles for syncing.
when it's ready to implement syncing, i'll give it a go and will try to add parse support.

thanks!

**Comment by drewmccormack** [comment]
Sounds great!
Like I said, when you come to adding Parse, I strongly recommend just copying CDECloudKitFileSystem, and adapting that with calls to Parse instead.
